services:
  postgres:
    image: postgres:15-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: ${POSTGRES_USER:-auth_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-auth_admin} -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: auth-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: auth-kafka
    depends_on: [zookeeper]
    ports: ["9093:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: auth-mailhog
    ports: ["1026:1025", "8026:8025"]

  app:
    build: .
    container_name: auth-app
    ports: ["8090:8090"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-auth_admin}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
      SPRING_KAFKA_BOOTSTRAP: kafka:9092
      JWT_SECRET: ${JWT_SECRET:-YXV0aC1wbGF0Zm9ybS1kZW1vLXNlY3JldC0yMDI2ISEhISEh}
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_DEMO_LOG: "false"
      FRONTEND_URL: http://localhost:5174
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  pgdata:
